### ISSUE TITLE
Minimum patch size for VGG16 is 32x32

### ISSUE THREAD

**Issue by e-chong** [e-chong/Singapore-Ship-Detection#2]
Downsampling the Kaggle images to match the Sentinel-2 resolution gives 30x30 patches, but VGG16 requires a minimum of 32x32.

We could either downsample Kaggle a little less or remove one of the convolutional layers from VGG16.

**Comment by jmlasalle** [comment]
That seems like a pretty solid reason to use 32 for oatch size if that will get us better results. Have you tried running it that way yet?
